FROM quay.io/footloose/ubuntu18.04

LABEL com.owner="www.dev-ops.de" \
      com.version="0.1.2"

RUN mkdir -p /www/bin
COPY config/bashrc /root/.bashrc
RUN rm -f /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime