FROM diceone/centos7:0.1.8

LABEL com.owner="www.dev-ops.de" \
      com.version="0.1.8"

RUN yum install -y docker iptables && systemctl enable docker
RUN curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
RUN ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
COPY /config/docker-compose@.service /etc/systemd/system/docker-compose@.service

