version: "2"
services:
  app:
    image: jenkins:2.60.3-alpine
    privileged: true
    container_name: jenkins
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - /data/service:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    restart: on-failure