name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag docker.pkg.github.com/diceone/centos:$(date +%s)
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/diceone/centos:$(date +%s)
